/*

function dosomething() {
	throw new Error(
		'a error is thrown from dosomething');
}

function init() {
	try {
		dosomething();
	}
	catch (e) {
		console.log(e);
	}
	console.log(
		"After successful error handling");
}

init();


const fs = require("fs");

fs.readFile('foo.txt', function (err, data) {
	if (err) {
		console.error(err);
	}
	else {
		console.log(data.toString());
	}
});

console.log("Program Ended");
*/

